creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
        # Bitwarden: Editor Key
        - age1jduzksjl7nsegr9h5mngfpthzwc52tcj4f82cyjert9qsr4rxufs96wt45
        
        # Host Key "pc"
        - age1sgg2e5twr0sf4mcawcxmetwa2xl3lvlh0k2d7s0k7fdus3vrkeyq3htp54

        # Host Key "p16s"
        - age1pp542rr87ezr7lffhm7xpymtc3p3g8eg4gqswv8vqp5metewpflqhukphf
